// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: authsvc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthType int32

const (
	AuthType_UNKNOWN AuthType = 0
	AuthType_JWT     AuthType = 1
)

// Enum value maps for AuthType.
var (
	AuthType_name = map[int32]string{
		0: "UNKNOWN",
		1: "JWT",
	}
	AuthType_value = map[string]int32{
		"UNKNOWN": 0,
		"JWT":     1,
	}
)

func (x AuthType) Enum() *AuthType {
	p := new(AuthType)
	*p = x
	return p
}

func (x AuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_authsvc_proto_enumTypes[0].Descriptor()
}

func (AuthType) Type() protoreflect.EnumType {
	return &file_authsvc_proto_enumTypes[0]
}

func (x AuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthType.Descriptor instead.
func (AuthType) EnumDescriptor() ([]byte, []int) {
	return file_authsvc_proto_rawDescGZIP(), []int{0}
}

type CreateClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Secret   []byte   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	UserID   string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	AuthType AuthType `protobuf:"varint,4,opt,name=authType,proto3,enum=authsvc.AuthType" json:"authType,omitempty"`
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authsvc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authsvc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return file_authsvc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateClientRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateClientRequest) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *CreateClientRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *CreateClientRequest) GetAuthType() AuthType {
	if x != nil {
		return x.AuthType
	}
	return AuthType_UNKNOWN
}

type RemoveClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *RemoveClientRequest) Reset() {
	*x = RemoveClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authsvc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveClientRequest) ProtoMessage() {}

func (x *RemoveClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authsvc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveClientRequest.ProtoReflect.Descriptor instead.
func (*RemoveClientRequest) Descriptor() ([]byte, []int) {
	return file_authsvc_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveClientRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type FindClientByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *FindClientByIDRequest) Reset() {
	*x = FindClientByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authsvc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindClientByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindClientByIDRequest) ProtoMessage() {}

func (x *FindClientByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authsvc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindClientByIDRequest.ProtoReflect.Descriptor instead.
func (*FindClientByIDRequest) Descriptor() ([]byte, []int) {
	return file_authsvc_proto_rawDescGZIP(), []int{2}
}

func (x *FindClientByIDRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type CreateClientReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateClientReply) Reset() {
	*x = CreateClientReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authsvc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateClientReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientReply) ProtoMessage() {}

func (x *CreateClientReply) ProtoReflect() protoreflect.Message {
	mi := &file_authsvc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientReply.ProtoReflect.Descriptor instead.
func (*CreateClientReply) Descriptor() ([]byte, []int) {
	return file_authsvc_proto_rawDescGZIP(), []int{3}
}

type RemoveClientReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveClientReply) Reset() {
	*x = RemoveClientReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authsvc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveClientReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveClientReply) ProtoMessage() {}

func (x *RemoveClientReply) ProtoReflect() protoreflect.Message {
	mi := &file_authsvc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveClientReply.ProtoReflect.Descriptor instead.
func (*RemoveClientReply) Descriptor() ([]byte, []int) {
	return file_authsvc_proto_rawDescGZIP(), []int{4}
}

type FindClientByIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *FindClientByIDReply) Reset() {
	*x = FindClientByIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authsvc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindClientByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindClientByIDReply) ProtoMessage() {}

func (x *FindClientByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_authsvc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindClientByIDReply.ProtoReflect.Descriptor instead.
func (*FindClientByIDReply) Descriptor() ([]byte, []int) {
	return file_authsvc_proto_rawDescGZIP(), []int{5}
}

func (x *FindClientByIDReply) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *FindClientByIDReply) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

var File_authsvc_proto protoreflect.FileDescriptor

var file_authsvc_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x22, 0x84, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x2d, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x11, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x25, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x27, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22,
	0x13, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x3d, 0x0a, 0x13, 0x46, 0x69, 0x6e,
	0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x2a, 0x20, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x4a, 0x57, 0x54, 0x10, 0x01, 0x32, 0xf7, 0x01, 0x0a, 0x0b, 0x41,
	0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x73, 0x76, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73,
	0x76, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x50, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x42, 0x79, 0x49, 0x44, 0x12, 0x1e, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2d, 0x6f, 0x77, 0x6c, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_authsvc_proto_rawDescOnce sync.Once
	file_authsvc_proto_rawDescData = file_authsvc_proto_rawDesc
)

func file_authsvc_proto_rawDescGZIP() []byte {
	file_authsvc_proto_rawDescOnce.Do(func() {
		file_authsvc_proto_rawDescData = protoimpl.X.CompressGZIP(file_authsvc_proto_rawDescData)
	})
	return file_authsvc_proto_rawDescData
}

var file_authsvc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_authsvc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_authsvc_proto_goTypes = []interface{}{
	(AuthType)(0),                 // 0: authsvc.AuthType
	(*CreateClientRequest)(nil),   // 1: authsvc.CreateClientRequest
	(*RemoveClientRequest)(nil),   // 2: authsvc.RemoveClientRequest
	(*FindClientByIDRequest)(nil), // 3: authsvc.FindClientByIDRequest
	(*CreateClientReply)(nil),     // 4: authsvc.CreateClientReply
	(*RemoveClientReply)(nil),     // 5: authsvc.RemoveClientReply
	(*FindClientByIDReply)(nil),   // 6: authsvc.FindClientByIDReply
}
var file_authsvc_proto_depIdxs = []int32{
	0, // 0: authsvc.CreateClientRequest.authType:type_name -> authsvc.AuthType
	1, // 1: authsvc.AuthService.CreateClient:input_type -> authsvc.CreateClientRequest
	2, // 2: authsvc.AuthService.RemoveClient:input_type -> authsvc.RemoveClientRequest
	3, // 3: authsvc.AuthService.FindClientByID:input_type -> authsvc.FindClientByIDRequest
	4, // 4: authsvc.AuthService.CreateClient:output_type -> authsvc.CreateClientReply
	5, // 5: authsvc.AuthService.RemoveClient:output_type -> authsvc.RemoveClientReply
	6, // 6: authsvc.AuthService.FindClientByID:output_type -> authsvc.FindClientByIDReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_authsvc_proto_init() }
func file_authsvc_proto_init() {
	if File_authsvc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authsvc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authsvc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authsvc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindClientByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authsvc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateClientReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authsvc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveClientReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authsvc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindClientByIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authsvc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authsvc_proto_goTypes,
		DependencyIndexes: file_authsvc_proto_depIdxs,
		EnumInfos:         file_authsvc_proto_enumTypes,
		MessageInfos:      file_authsvc_proto_msgTypes,
	}.Build()
	File_authsvc_proto = out.File
	file_authsvc_proto_rawDesc = nil
	file_authsvc_proto_goTypes = nil
	file_authsvc_proto_depIdxs = nil
}
